### ISSUE TITLE
Product page gallery: image height is no longer hardcoded

### ISSUE THREAD

**Issue by jtomaszewski** [magesuite/theme-creativeshop#46]
[This commit](https://github.com/magesuite/theme-creativeshop/commit/123141d90b83701be211c25ee0ccfd21ae4e5f39#diff-8a193bc23e283dd24afe88c25de9b23fb4a7ed26b92d73eadb28ca44bd4775bbL40) ( cc @krzksz ) removed `$loaderPadding` from being used in the `Magento_Catalog/templates/product/view/gallery.phtml` . Now, the product page content "jumps" after image is loaded.

Instead, we could keep on using `$loaderPadding` so that we "hardcode" the img container's height, so that the browser doesn't have to rerender its' surroundings after image is loaded.

Do you mind bringing it back? I could submit a PR.

**Comment by mborkowski** [comment]
Hi @jtomaszewski,
We have recently removed that in favour of bringing `width` and `height` attributes for the image. This operation was done for a couple of reasons, and one of them was to improve also layout shifts. This was done [18 days ago](https://github.com/magesuite/theme-creativeshop/commit/435fce8cba3630a89260c1bead5264c737caac19). Please check if this will work for you.

**Comment by jtomaszewski** [comment]
I think it's better. Although I still have a feeling that the thumbnails under the main picture

![image](https://user-images.githubusercontent.com/1862580/107845413-7568cd00-6ddb-11eb-9378-c82a79fc4d0c.png)

appear only after client-side render, which causes CLS. 

So what we've done, is we've added something like that to `product-gallery.scss`:

```scss

// margin-bottom of `.fotorama__stage`
$fotorama-padding-bottom: 0.4rem;
// height of `.fotorama__nav-wrap`
$fotorama-nav-mobile-height: 35px;
$fotorama-nav-desktop-height: 91px;

.cs-product-gallery {
    $root: &;

    &__placeholder {
        margin: 0 auto;
        padding: ($fotorama-padding-bottom / 2) 0;

        &__inner {
            position: relative;
            overflow: hidden;
        }

        &__inner-before {
            content: '';
            width: 1px;
            margin-left: -1px;
            float: left;
            height: 0;
        }

        &__inner-image {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        &:after {
            content: '';
            display: table;
            clear: both;
        }
    }

    &__nav-placeholder {
        &:last-child {
            height: $fotorama-nav-mobile-height - 1px;
            @include media('>=tablet') {
                height: $fotorama-nav-desktop-height - 1px;
            }
        }
    }

    // Always show the navigation,
    // even if it's empty
    // (to minimize layout shift)
    .fotorama {
        min-height: $fotorama-nav-mobile-height - 1px;
        @include media('>=tablet') {
            min-height: $fotorama-nav-desktop-height - 1px;
        }
    }

    // Always show the navigation,
    // even if it's empty
    // (to minimize layout shift)
    .fotorama__nav-wrap {
        display: block !important;
        &[style='display: none;'] {
            visibility: hidden;
        }
        height: $fotorama-nav-mobile-height - 1px;
        @include media('>=tablet') {
            height: $fotorama-nav-desktop-height - 1px;
        }
    }
}
```

Thanks to it, the row for fotorama thumbnails appears always with constant height (if product has no pictures, it just shows blank space).

Let me know if u'd be interested in a PR for that.

In the meantime, I'll close this issue.
